apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dotnettest-trigger-template.yaml
- dotnettest-trigger.yaml
- php-hello-trigger-template.yaml
- php-hello-trigger.yaml
- el-dotnettest-route.yaml
- el-php-hello-route.yaml